name: Autoupdate wraps

on:
  schedule:
    - cron: "15 0 * * 0"
    - cron: "15 0 * * 4"
  workflow_dispatch:
    inputs:
      wraps:
        description: Update only these wraps (space-separated, optional)
        required: false
        type: string

permissions:
  # everything uses personal access tokens
  contents: none

# don't race with ourselves or prune.yml
concurrency: autoupdate

env:
  # repo to send PRs to
  BASE_REPO: mesonbuild/wrapdb
  # repo to send PRs from
  HEAD_REPO: wrapdb-bot/wrapdb

# Tokens:
# BASE_TOKEN
#    Classic token with public_repo scope, for accessing BASE_REPO.
# HEAD_TOKEN
#    Fine-grained token with R/W code + workflow access to HEAD_REPO.
#    Workflow access is needed for syncing upstream commits that update
#    GitHub Actions workflows.  This is safe because GitHub Actions is
#    disabled in HEAD_REPO.
# KEEPALIVE_TOKEN
#    R/W actions access to this repo, for refreshing the 60-day workflow
#    timeout.

jobs:
  check:
    name: Check for updates
    runs-on: ubuntu-slim
    outputs:
      matrix: ${{ steps.check.outputs.matrix }}
    steps:
      - name: Check out base repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BASE_TOKEN }}
          repository: ${{ env.BASE_REPO }}
      - name: Check for updates
        id: check
        run: tools/versions.py list --github --official --update ${{ inputs.wraps }} >> $GITHUB_OUTPUT
      - name: Report untracked wraps
        run: |
          echo "## Manual update required" >> $GITHUB_STEP_SUMMARY
          tools/versions.py list --markdown --port --update >> $GITHUB_STEP_SUMMARY
          echo "## Not configured in [Anitya](https://release-monitoring.org/)" >> $GITHUB_STEP_SUMMARY
          tools/versions.py list --markdown --untracked >> $GITHUB_STEP_SUMMARY
      # Prevent GitHub from disabling the workflow after 60 days
      - name: Keep workflow alive
        env:
          GITHUB_TOKEN: ${{ secrets.KEEPALIVE_TOKEN }}
        run: gh workflow enable -R ${{ github.repository }} autoupdate.yml

  update:
    name: Update
    needs: check
    runs-on: ubuntu-slim
    if: fromJson(needs.check.outputs.matrix).include[0]
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.check.outputs.matrix) }}
    steps:
      - name: Check out base repo
        uses: actions/checkout@v5
        with:
          token: ${{ secrets.BASE_TOKEN }}
          repository: ${{ env.BASE_REPO }}
      - name: Update
        id: update
        run: |
          tools/versions.py autoupdate "${{ matrix.wrap }}"

          git config set user.name "WrapDB Bot"
          git config set user.email "179637176+wrapdb-bot@users.noreply.github.com"
          tools/versions.py commit
          echo "commit-subject=$(git log -1 --format=%s)" >> $GITHUB_OUTPUT

          cat > ${{ runner.temp }}/pull-description <<EOF
          [Automated PR](${{ github.server_url }}/${{ github.repository }}/actions/workflows/autoupdate.yml) by WrapDB Bot.

          EOF
          if jq -e ".[\"${{ matrix.wrap }}\"]" < ci_config.json > ${{ runner.temp }}/ci-config; then
            cat >> ${{ runner.temp }}/pull-description <<EOF
          \`ci_config.json\`:
          \`\`\`json
          $(cat ${{ runner.temp }}/ci-config)
          \`\`\`
          EOF
          else
            echo 'No configuration in `ci_config.json`.' >> ${{ runner.temp }}/pull-description
          fi
      - name: Check for closed pull request
        id: check-closed
        env:
          GITHUB_TOKEN: ${{ secrets.BASE_TOKEN }}
        run: |
          # log the details of any PR we find
          # head: is a prefix match, so we check again with jq
          if gh pr list \
                  --search "state:closed is:unmerged author:${HEAD_REPO%/*} head:auto/${{ matrix.wrap }}" \
                  --json headRefName,title,url | \
                  jq -e ".[] | select(
                      .headRefName == \"auto/${{ matrix.wrap }}\" and
                      (.title | endswith(\"to ${{ matrix.new-version }}\"))
                  )"; then
              # create-pull-request handles updating the branch, so we end
              # up skipping that too.  We don't want to delete the branch
              # because that would prevent manual reopening of the PR, but
              # we leave it stale unless and until the PR is reopened.
              echo "Found closed PR for this version; skipping branch update and PR"
          else
              echo "send-pull=true" >> $GITHUB_OUTPUT
          fi
      - name: Create pull request
        uses: peter-evans/create-pull-request@v7
        if: steps.check-closed.outputs.send-pull
        with:
          token: ${{ secrets.BASE_TOKEN }}
          branch-token: ${{ secrets.HEAD_TOKEN }}
          push-to-fork: ${{ env.HEAD_REPO }}
          branch: auto/${{ matrix.wrap }}
          title: ${{ steps.update.outputs.commit-subject }}
          body-path: ${{ runner.temp }}/pull-description
          maintainer-can-modify: false
